import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import '@coinbase/onchainkit/styles.css';
import { OnchainKitProvider } from "@coinbase/onchainkit"
import { base } from "viem/chains";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <OnchainKitProvider
        apiKey={process.env.ONCHAINKIT_API_KEY}
        chain={base}
        config={{
          appearance: {
            name: 'Your App Name',        // Displayed in modal header
            logo: 'https://your-logo.com',// Displayed in modal header
            mode: 'auto',                 // 'light' | 'dark' | 'auto'
            theme: 'default',             // 'default' or custom theme
          },
          // configure the wallet modal below
          wallet: {
            display: 'modal',
            termsUrl: 'https://...',
            privacyUrl: 'https://...',
          },
        }}
        >
        {children}
        </OnchainKitProvider>
      </body>
    </html>
  );
}
